"""init_tables

Revision ID: e4956b7f76dc
Revises: 
Create Date: 2026-03-19 20:34:05.937197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4956b7f76dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'total_quantity',
               existing_type=mysql.INTEGER(unsigned=True),
               comment=None,
               existing_comment='总库存',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory', 'available_quantity',
               existing_type=mysql.INTEGER(unsigned=True),
               comment=None,
               existing_comment='可用库存',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory', 'locked_quantity',
               existing_type=mysql.INTEGER(unsigned=True),
               comment=None,
               existing_comment='锁定库存',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory', 'version',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='乐观锁版本号',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_sku_id'), table_name='inventory')
    op.drop_index(op.f('idx_warehouse_id'), table_name='inventory')
    op.create_index(op.f('ix_inventory_sku_id'), 'inventory', ['sku_id'], unique=False)
    op.create_index(op.f('ix_inventory_warehouse_id'), 'inventory', ['warehouse_id'], unique=False)
    op.alter_column('inventory_lock', 'lock_status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment=None,
               existing_comment='1-锁定中 2-已扣减 3-已释放',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('inventory_lock', 'expire_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='锁定期限',
               existing_nullable=False)
    op.alter_column('inventory_lock', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory_lock', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_order_id'), table_name='inventory_lock')
    op.create_index(op.f('ix_inventory_lock_order_id'), 'inventory_lock', ['order_id'], unique=False)
    op.alter_column('inventory_transaction', 'change_type',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment=None,
               existing_comment='1-入库 2-出库 3-锁定 4-解锁',
               existing_nullable=False)
    op.alter_column('inventory_transaction', 'business_type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='业务类型：采购/销售/退货等',
               existing_nullable=True)
    op.alter_column('inventory_transaction', 'business_id',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='业务单号',
               existing_nullable=True)
    op.alter_column('inventory_transaction', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_business_id'), table_name='inventory_transaction')
    op.drop_index(op.f('idx_created_at'), table_name='inventory_transaction')
    op.drop_index(op.f('idx_sku_warehouse'), table_name='inventory_transaction')
    op.create_index(op.f('ix_inventory_transaction_business_id'), 'inventory_transaction', ['business_id'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_sku_id'), 'inventory_transaction', ['sku_id'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_warehouse_id'), 'inventory_transaction', ['warehouse_id'], unique=False)
    op.alter_column('sku', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment=None,
               existing_comment='1-启用 0-禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('sku', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sku', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_sku_code'), table_name='sku')
    op.alter_column('warehouse', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment=None,
               existing_comment='1-启用 0-禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('warehouse', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('warehouse', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_warehouse_code'), table_name='warehouse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_warehouse_code'), 'warehouse', ['warehouse_code'], unique=False)
    op.alter_column('warehouse', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('warehouse', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('warehouse', 'status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='1-启用 0-禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.create_index(op.f('idx_sku_code'), 'sku', ['sku_code'], unique=False)
    op.alter_column('sku', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('sku', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sku', 'status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='1-启用 0-禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('ix_inventory_transaction_warehouse_id'), table_name='inventory_transaction')
    op.drop_index(op.f('ix_inventory_transaction_sku_id'), table_name='inventory_transaction')
    op.drop_index(op.f('ix_inventory_transaction_business_id'), table_name='inventory_transaction')
    op.create_index(op.f('idx_sku_warehouse'), 'inventory_transaction', ['sku_id', 'warehouse_id'], unique=False)
    op.create_index(op.f('idx_created_at'), 'inventory_transaction', ['created_at'], unique=False)
    op.create_index(op.f('idx_business_id'), 'inventory_transaction', ['business_id'], unique=False)
    op.alter_column('inventory_transaction', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory_transaction', 'business_id',
               existing_type=mysql.VARCHAR(length=64),
               comment='业务单号',
               existing_nullable=True)
    op.alter_column('inventory_transaction', 'business_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='业务类型：采购/销售/退货等',
               existing_nullable=True)
    op.alter_column('inventory_transaction', 'change_type',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='1-入库 2-出库 3-锁定 4-解锁',
               existing_nullable=False)
    op.drop_index(op.f('ix_inventory_lock_order_id'), table_name='inventory_lock')
    op.create_index(op.f('idx_order_id'), 'inventory_lock', ['order_id'], unique=False)
    op.alter_column('inventory_lock', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('inventory_lock', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory_lock', 'expire_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='锁定期限',
               existing_nullable=False)
    op.alter_column('inventory_lock', 'lock_status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='1-锁定中 2-已扣减 3-已释放',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('ix_inventory_warehouse_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_sku_id'), table_name='inventory')
    op.create_index(op.f('idx_warehouse_id'), 'inventory', ['warehouse_id'], unique=False)
    op.create_index(op.f('idx_sku_id'), 'inventory', ['sku_id'], unique=False)
    op.alter_column('inventory', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('inventory', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory', 'version',
               existing_type=mysql.INTEGER(),
               comment='乐观锁版本号',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory', 'locked_quantity',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='锁定库存',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory', 'available_quantity',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='可用库存',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory', 'total_quantity',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='总库存',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
